### ISSUE TITLE
Dataview query  syntax 

### ISSUE THREAD

**Issue by warhar** [Heiss/obsidian-vikunja-plugin#18]
So far, so good, the plugin is pulling and pushing tasks as expected, thank you. Now I'd like to sort what's coming in to only include tasks that fit a certain criteria. (e.g. groups, labels, etc) Is this possible by querying Dataview directly? If so, could you help me with a few examples to get me started :)

**Comment by Heiss** [comment]
That is currently not implemented and can only be done via sourcecode. I could integrate such things via settings. What would you expect to set? Currently it is a very simple query via dataviewjs https://github.com/Heiss/obsidian-vikunja-plugin/blob/4af5c20c0645b3a537de321840894ec0b762fec6/src/vaultSearcher/dataviewSearcher.ts#L43.

**Comment by warhar** [comment]
Could we incorporate into the settings: filters, sorting, and grouping the tasks that pull in, like the Todoist plugin does with their dataview queries? (Filters by due date and by project. Sorting by priority. Grouping by project.)

**Comment by Heiss** [comment]
Okay for clarification:
Dataview is only used to get the tasks from the obsidian vault. I could doing it on my own, but dataview is dead simple.
To filter tasks coming from vikunja, currently you can only set the default project where tasks will be pushed to or be pulled from, which is like a primitive filter.

Grouping does not makes sense in obsidian context, because markdown does not have any of such feature for tasks.

Labels can be set through obsidian and vikunja, so how should the label filter apply? Should it apply on both ends or only on vikunja side? But what happens with tasks on obsidian side with the same label? Will it be ignored and not synced at all? Many questions about how syncing should work pops up...

Sorting could be possible, but it only would means, that new tasks from vikunja will be sorted, no modification of existing ones. I cannot see any benefits to do so.

If you would like to get different views, i would recommend to set up a specific file for your tasks pulled from vikunja and using dataviewjs in your daily notes or anywhere else to get the wanted view into your tasks. This is way more flexible and robust, because no fiddling around with the vikunja api. ;) (And this plugin can be still fairly focussed on syncing fairly all tasks.) So you can using tasks anywhere in obsidian, which will be pushed to vikunja and the single file for all pulled tasks. With dataview you get your filter.

Currently there is no representation of priority or vikunja project, but it could be added in the future, to create such filters on your own. But nevertheless, the plugin would sync ALL tasks from and to vikunja.

**Comment by warhar** [comment]
Thank you for the clarification, now I understand the workflow of the plugin. This just made my day, I'll make some adjustments and see how it goes, thank you for your patience. Any updates planned to look forward to :-)
